### ISSUE TITLE
Request for removal of copyrighted files

### ISSUE THREAD

**Issue by dockimbel** [freered/Code#2]
I am the original author of several files in this repo, which were taken from my gists or different other sources, without my permission, without mention of the author (for some) and without original source link. Those files are not released under "public domain", nor any open source licence, so [copyright laws apply](https://help.github.com/articles/licensing-a-repository/). Therefore, I demand the removal of the following files without any delay:
```
gui/color-sliders.red
gui/livecode.red
gui/Livecode%2520enhanced
gui/worm.red
rebol/profiler2.r
utils/JSON.red
utils/brainfuck.red
utils/to-Roman.red
```
Failure to comply will be signaled to Github team for further actions.

**Comment by iArnold** [comment]
Hello Nenad,

No problem, I will take care of the removal.

Best regards,

Arnold

**Comment by iArnold** [comment]
Hello Nenad,

I have removed the named files from the repository.
Apologies for the inconvenience.

Best regards,

Arnold
